### ISSUE TITLE
Segfault with RS-INTEROUTE

### ISSUE THREAD

**Issue by devicenull** [snar/bgpq3#38] opened 2018-06-01 20:49 UTC
<pre>
bgpq3 -j -4 RS-INTEROUTE
</pre>

gdb suggests the issue is around here

<pre>
Program received signal SIGSEGV, Segmentation fault.
0x000000000040644f in bgpq_expand_irrd (b=0x7ffffff7e170,
    callback=0x404c7c <bgpq_expanded_prefix>, udata=0x0, fmt=0x410b37 "!i%s,1\n")
    at bgpq_expander.c:645
645                             memcpy(recvbuffer, eon+1, off - ((eon+1)-response));
</pre>

**Comment by devicenull** [comment] 2018-06-01 20:59
FWIW, the response here ends up being 'A23697440', so it seems to just be allocating too much memory?

**Comment by snar** [comment] 2018-06-03 13:11
On Fri, Jun 01, 2018 at 01:49:32PM -0700, devicenull wrote:
> bgpq3 -j -4 RS-INTEROUTE

Unable to reproduce :( FreeBSD 10-stable, bgpq3 just build from HEAD.

> gdb suggests the issue is around here

Can you provide more details, like backtrace ?

**Comment by devicenull** [comment] 2018-06-04 13:47
Thanks, I can confirm this works properly with HEAD now.

**Comment by job** [comment] 2018-07-20 15:21
@devicenull close this issue then! :)

**Closed** 2018-07-20 17:55 UTC
